
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type ServerProductPageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type ServerProductPageQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, description: Maybe<string>, titleTemplate: Maybe<string>, siteUrl: Maybe<string> }> }> };


// Query Related Code

export const ServerProductPageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query ServerProductPageQuery {\n  site {\n    siteMetadata {\n      title\n      description\n      titleTemplate\n      siteUrl\n    }\n  }\n}\n",
  sha256Hash: "d0cc54e797bdbc7dee57b040c49f24fd19606cc4ad5655544986588ea7ffa10d",
  operationName: "ServerProductPageQuery",
}

