
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type HomePageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type HomePageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ siteUrl: Maybe<string> }> }> };


// Query Related Code

export const HomePageSEOQuery = {
  query: "query HomePageSEOQuery {\n  site {\n    siteMetadata {\n      siteUrl\n    }\n  }\n}\n",
  sha256Hash: "b09232f730564d8ebb52eebfb9818487261cdae502aed28b7ab4a8a6f5c47fb9",
  operationName: "HomePageSEOQuery",
}

