
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type HomePageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type HomePageQueryQuery = { cmsSeo: Maybe<{ seo: Maybe<{ facebook: Maybe<{ title: Maybe<string>, description: Maybe<string>, thumbnail: Maybe<string> }>, siteMetadata: Maybe<{ title: Maybe<string>, description: Maybe<string>, titleTemplate: Maybe<string> }> }> }>, cmsHome: Maybe<{ sections: Array<{ name: string, props: any }> }> };


// Query Related Code

export const HomePageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query HomePageQuery {\n  cmsSeo {\n    seo {\n      facebook {\n        title\n        description\n        thumbnail\n      }\n      siteMetadata {\n        title\n        description\n        titleTemplate\n      }\n    }\n  }\n  cmsHome {\n    sections {\n      name\n      props\n    }\n  }\n}\n",
  sha256Hash: "1033fc00b8245005af05253f1ac8fa9802708a9725833c7b5c058eae4f7bdc4f",
  operationName: "HomePageQuery",
}

