
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type StoreSearchPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type StoreSearchPageSeoQueryQuery = { cmsSeo: Maybe<{ seo: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, description: Maybe<string>, titleTemplate: Maybe<string> }> }> }> };


// Query Related Code

export const StoreSearchPageSEOQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query StoreSearchPageSEOQuery {\n  cmsSeo {\n    seo {\n      siteMetadata {\n        title\n        description\n        titleTemplate\n      }\n    }\n  }\n}\n",
  sha256Hash: "f93abd185a6a8e65bdbef56cfc1193aee35370e252e4c7f407fddb31fe8f4d2f",
  operationName: "StoreSearchPageSEOQuery",
}

