
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type SearchPageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type SearchPageQueryQuery = { cmsSeo: Maybe<{ seo: Maybe<{ siteMetadata: Maybe<{ titleTemplate: Maybe<string>, title: Maybe<string>, description: Maybe<string> }> }> }> };


// Query Related Code

export const SearchPageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query SearchPageQuery {\n  cmsSeo {\n    seo {\n      siteMetadata {\n        titleTemplate\n        title\n        description\n      }\n    }\n  }\n}\n",
  sha256Hash: "1a3f886d968788432fdfa93cfff50fed00c26fad2b541ae9fc40876a110ecf1e",
  operationName: "SearchPageQuery",
}

