

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type SearchPageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type SearchPageQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ titleTemplate: Maybe<string>, title: Maybe<string>, description: Maybe<string> }> }> };


// Query Related Code

export const SearchPageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query SearchPageQuery {\n  site {\n    siteMetadata {\n      titleTemplate\n      title\n      description\n    }\n  }\n}\n",
  sha256Hash: "2ae563d9f1979d26963b149d71c1305765a5fc8ceb1e3beb1b307cfc7751c9f4",
  operationName: "SearchPageQuery",
}

