
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type StoreProductPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type StoreProductPageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ siteUrl: Maybe<string> }> }>, seo: Maybe<{ extraBlocks: Array<Maybe<{ blocks: Array<{ name: string, props: Maybe<any> }> }>> }> };


// Query Related Code

export const StoreProductPageSEOQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query StoreProductPageSEOQuery {\n  site {\n    siteMetadata {\n      siteUrl\n    }\n  }\n  seo: vtexCmsPageContent(type: {eq: \"seo\"}) {\n    extraBlocks {\n      blocks {\n        name\n        props\n      }\n    }\n  }\n}\n",
  sha256Hash: "095f72a5d82051da1bb8484949aa6b1ead93c72ec1123538dd211621a24d3a88",
  operationName: "StoreProductPageSEOQuery",
}

