
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type ServerProductPageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type ServerProductPageQueryQuery = { cmsSeo: Maybe<{ seo: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, description: Maybe<string>, titleTemplate: Maybe<string> }> }> }> };


// Query Related Code

export const ServerProductPageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query ServerProductPageQuery {\n  cmsSeo {\n    seo {\n      siteMetadata {\n        title\n        description\n        titleTemplate\n      }\n    }\n  }\n}\n",
  sha256Hash: "04f4f7688907dcbfa1b038e862794f143a6e81f1a2e738a923043d7e6eb2d094",
  operationName: "ServerProductPageQuery",
}

