

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type CollectionSeoFragment_StoreCollectionFragment = { seo: { title: string, description: string } };


// Query Related Code

