
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type StoreSearchPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type StoreSearchPageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ siteUrl: Maybe<string> }> }>, seo: Maybe<{ extraBlocks: Array<Maybe<{ blocks: Array<{ name: string, props: Maybe<any> }> }>> }> };


// Query Related Code

export const StoreSearchPageSEOQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query StoreSearchPageSEOQuery {\n  site {\n    siteMetadata {\n      siteUrl\n    }\n  }\n  seo: vtexCmsPageContent(type: {eq: \"seo\"}) {\n    extraBlocks {\n      blocks {\n        name\n        props\n      }\n    }\n  }\n}\n",
  sha256Hash: "6da31d471527703e3346214989a3a8bf22e1dc209b5ea0edcf3c5c3613aba783",
  operationName: "StoreSearchPageSEOQuery",
}

