
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type StoreSearchPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type StoreSearchPageSeoQueryQuery = { seo: Maybe<{ extraBlocks: Array<Maybe<{ blocks: Array<{ name: string, props: Maybe<any> }> }>> }> };


// Query Related Code

export const StoreSearchPageSEOQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query StoreSearchPageSEOQuery {\n  seo: vtexCmsPageContent(type: {eq: \"seo\"}) {\n    extraBlocks {\n      blocks {\n        name\n        props\n      }\n    }\n  }\n}\n",
  sha256Hash: "c2f9f2304e3c79ed99d177267785aef8cd1099e5540f4b42f55c1f9dd337728d",
  operationName: "StoreSearchPageSEOQuery",
}

