

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type CollectionSeoFragment_BreadcrumbFragment = { href: Maybe<string>, name: Maybe<string> };


// Query Related Code

