

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type Data_CarouselFragmentFragment = { id: string, slice_type: string, primary: Maybe<{ display_arrows: Maybe<boolean>, display_dots: Maybe<boolean>, title: Maybe<{ text: Maybe<string> }> }>, items: Maybe<Array<Maybe<{ items: Maybe<{ alt: Maybe<string>, gatsbyImageData: Maybe<any> }> }>>> };


// Query Related Code

