

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type GalleryQueryQueryVariables = Exact<{
  first: Scalars['Int'];
  after: Maybe<Scalars['String']>;
  sort: Maybe<StoreSort>;
  term: Maybe<Scalars['String']>;
  selectedFacets: Array<StoreSelectedFacet> | StoreSelectedFacet;
}>;


export type GalleryQueryQuery = { search: { products: { pageInfo: { totalCount: number }, edges: Array<{ node: { slug: string, name: string, sku: string, id: string, image: Array<{ url: string, alternateName: string }> } }> } } };


// Query Related Code

export const GalleryQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query GalleryQuery($first: Int!, $after: String, $sort: StoreSort, $term: String, $selectedFacets: [StoreSelectedFacet!]!) {\n  search(\n    first: $first\n    after: $after\n    sort: $sort\n    term: $term\n    selectedFacets: $selectedFacets\n  ) {\n    products {\n      pageInfo {\n        totalCount\n      }\n      edges {\n        node {\n          id: productID\n          slug\n          name\n          sku\n          image {\n            url\n            alternateName\n          }\n        }\n      }\n    }\n  }\n}\n",
  sha256Hash: "5071d3b7aff8dac3887598c3749c02a8921d31cc331f4ab275f218b94c364854",
  operationName: "GalleryQuery",
}

