

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type PagesQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PagesQueryQuery = { allSiteFunction: { nodes: Array<{ functionRoute: string }> }, allSitePage: { nodes: Array<{ path: string }> } };


// Query Related Code

export const PagesQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query PagesQuery {\n  allSiteFunction {\n    nodes {\n      functionRoute\n    }\n  }\n  allSitePage(filter: {path: {ne: \"/dev-404-page/\"}}) {\n    nodes {\n      path\n    }\n  }\n}\n",
  sha256Hash: "1a6216b0c88247a59d361e256da3d2ecf2063fe7790e1ddb4d688ab8d7c56d0b",
  operationName: "PagesQuery",
}

