

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ProductGallery_ProductSearchFragment = { totalCount: Maybe<number> };


// Query Related Code

