

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ProductDetailsFragment_ProductFragment = { name: string, id: string, image: Array<{ url: string, alternateName: string }> };


// Query Related Code

