

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ProductDetailsFragment_ProductFragment = { sku: string, name: string, gtin: string, id: string, isVariantOf: { productGroupID: string, name: string }, image: Array<{ url: string, alternateName: string }>, brand: { name: string }, offers: { offers: Array<{ price: number, listPrice: number, seller: { identifier: string } }> } };


// Query Related Code

