

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ProductDetailsFragment_ProductFragment = { name: string, sku: string, id: string, image: Array<{ url: string, alternateName: string }>, offers: { offers: Array<{ price: number, listPrice: number, seller: { identifier: string } }> } };


// Query Related Code

