

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ProductGallery_ProductsFragment = { pageInfo: { totalCount: number } };


// Query Related Code

