

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type ValidateCartMutationMutationVariables = Exact<{
  cart: IStoreCart;
}>;


export type ValidateCartMutationMutation = { validateCart: Maybe<{ order: { orderNumber: string, acceptedOffer: Array<{ quantity: number, price: number, listPrice: number, seller: { identifier: string }, itemOffered: { sku: string, name: string, image: Array<{ url: string, alternateName: string }> } }> }, messages: Array<{ text: string, status: StoreStatus }> }> };


// Query Related Code

export const ValidateCartMutation = {
  query: process.env.NODE_ENV === 'production' ? undefined : "mutation ValidateCartMutation($cart: IStoreCart!) {\n  validateCart(cart: $cart) {\n    order {\n      orderNumber\n      acceptedOffer {\n        seller {\n          identifier\n        }\n        quantity\n        price\n        listPrice\n        itemOffered {\n          sku\n          name\n          image {\n            url\n            alternateName\n          }\n        }\n      }\n    }\n    messages {\n      text\n      status\n    }\n  }\n}\n",
  sha256Hash: "02af5481bca446f3bd38d91163da831b828d7e50a9209393d6edb4cf49203837",
  operationName: "ValidateCartMutation",
}

