name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - name: Setup BASE_SITE_URL Env Var.
        run: |
          echo "PR_HEAD_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BASE_SITE_URL=https://sfj-$(git rev-parse --short HEAD)--base.preview.vtex.app" >> $GITHUB_ENV
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          runs: 3
          configPath: ./lighthouserc.js
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true 
